### PR TITLE
Nav bar addition

### PR DESCRIPTION
**Pull request by randycarrero**
Nav Demo

This is how it will Look. used google chrome for photo. but tested on both IE and Google chrome. 
The Gray has been removed. and the text has also been changed to icons.

### CODE REVIEW

**Comment by nicolasdeory** [comment]
Is this ready for merging?

**Comment by randycarrero** [comment]
it should be i thought it was broken thats why i closed it. but i was using the wrong file.
Sorry about that.

**Comment by nicolasdeory** [comment]
Check the master branch when you can, I don't think it looks like the picture you sent, but it still works so I merged it.

**Comment by randycarrero** [comment]
Yes before it was not possible to hover the question mark. So some adjustments made so it can hover addition and made them all symmetrical

**Pull request merged**
